# Generated by Django 5.2.4 on 2025-08-04 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('popular_attractions', models.TextField(blank=True, help_text='JSON list of popular attractions')),
                ('average_daily_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(default='Day {day_number}', max_length=200)),
                ('activities', models.TextField(help_text='JSON list of activities for the day')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('destination_city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_count', models.IntegerField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('NGN', 'Nigerian Naira (₦)'), ('INR', 'Indian Rupee (₹)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)')], default='USD', max_length=3)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interests', models.TextField(help_text='Comma-separated interests')),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('tourist_attraction', 'Tourist Attraction'), ('museum', 'Museum'), ('park', 'Park'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('nightlife', 'Nightlife'), ('cultural', 'Cultural Site'), ('adventure', 'Adventure Activity'), ('religious', 'Religious Site'), ('historical', 'Historical Site'), ('nature', 'Nature'), ('other', 'Other')], max_length=50)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=200)),
                ('opening_hours', models.TextField(blank=True, help_text='JSON format opening hours')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('photos', models.TextField(blank=True, help_text='JSON list of photo references')),
                ('recommended_duration', models.IntegerField(blank=True, help_text='Recommended visit duration in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.itineraryday')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_interest', to='trips.tripplan')),
            ],
            options={
                'ordering': ['-rating', 'estimated_cost'],
            },
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='trips.tripplan'),
        ),
        migrations.CreateModel(
            name='HotelSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('amenities', models.TextField(blank=True, help_text='JSON list of amenities')),
                ('photos', models.TextField(blank=True, help_text='JSON list of photo references')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_suggestions', to='trips.tripplan')),
            ],
            options={
                'ordering': ['-rating', 'price_per_night'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together={('trip', 'day_number')},
        ),
    ]
