# Generated by Django 5.2.1 on 2025-08-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='accommodation_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hotel/accommodation budget', max_digits=10),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='activity_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Activities and sightseeing budget', max_digits=10),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='departure_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='departure_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='departure_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='departure_location',
            field=models.CharField(default='Lagos', help_text='Starting location (e.g., Lagos, Nigeria or New York, USA)', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripplan',
            name='departure_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='flight_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated flight costs', max_digits=10),
        ),
    ]
