# Generated by Django 5.2.4 on 2025-08-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tripplan_accommodation_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='departure_location',
            field=models.CharField(default='Unknown Location', help_text='Starting location (e.g., Lagos, Nigeria or New York, USA)', max_length=200),
        ),
    ]
